# nodepool-x86.yaml
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: x86-nodepool
spec:
  template:
    metadata:
      labels:
        dedicated: x86-workloads
    spec:
      expireAfter: 720h0m0s   # retire nodes after 30 days
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: x86-ec2nodeclass
      requirements:
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot", "on-demand"]
  limits:
    cpu: "500"
    memory: "500Gi"
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 30s
